{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "9cf458de-4506-4ac3-98c0-abfd5a274d3b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting streamlit\n",
      "  Downloading streamlit-1.53.0-py3-none-any.whl.metadata (10 kB)\n",
      "Collecting altair!=5.4.0,!=5.4.1,<7,>=4.0 (from streamlit)\n",
      "  Downloading altair-6.0.0-py3-none-any.whl.metadata (11 kB)\n",
      "Collecting blinker<2,>=1.5.0 (from streamlit)\n",
      "  Downloading blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)\n",
      "Collecting cachetools<7,>=5.5 (from streamlit)\n",
      "  Downloading cachetools-6.2.4-py3-none-any.whl.metadata (5.6 kB)\n",
      "Collecting click<9,>=7.0 (from streamlit)\n",
      "  Downloading click-8.3.1-py3-none-any.whl.metadata (2.6 kB)\n",
      "Requirement already satisfied: numpy<3,>=1.23 in c:\\users\\donyango\\appdata\\local\\programs\\python\\python314\\lib\\site-packages (from streamlit) (2.3.4)\n",
      "Requirement already satisfied: packaging>=20 in c:\\users\\donyango\\appdata\\local\\programs\\python\\python314\\lib\\site-packages (from streamlit) (25.0)\n",
      "Requirement already satisfied: pandas<3,>=1.4.0 in c:\\users\\donyango\\appdata\\local\\programs\\python\\python314\\lib\\site-packages (from streamlit) (2.3.3)\n",
      "Requirement already satisfied: pillow<13,>=7.1.0 in c:\\users\\donyango\\appdata\\local\\programs\\python\\python314\\lib\\site-packages (from streamlit) (12.0.0)\n",
      "Requirement already satisfied: protobuf<7,>=3.20 in c:\\users\\donyango\\appdata\\local\\programs\\python\\python314\\lib\\site-packages (from streamlit) (6.33.4)\n",
      "Requirement already satisfied: pyarrow>=7.0 in c:\\users\\donyango\\appdata\\local\\programs\\python\\python314\\lib\\site-packages (from streamlit) (22.0.0)\n",
      "Requirement already satisfied: requests<3,>=2.27 in c:\\users\\donyango\\appdata\\local\\programs\\python\\python314\\lib\\site-packages (from streamlit) (2.32.5)\n",
      "Collecting tenacity<10,>=8.1.0 (from streamlit)\n",
      "  Downloading tenacity-9.1.2-py3-none-any.whl.metadata (1.2 kB)\n",
      "Collecting toml<2,>=0.10.1 (from streamlit)\n",
      "  Downloading toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.10.0 in c:\\users\\donyango\\appdata\\local\\programs\\python\\python314\\lib\\site-packages (from streamlit) (4.15.0)\n",
      "Collecting watchdog<7,>=2.1.5 (from streamlit)\n",
      "  Downloading watchdog-6.0.0-py3-none-win_amd64.whl.metadata (44 kB)\n",
      "Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)\n",
      "  Downloading gitpython-3.1.46-py3-none-any.whl.metadata (13 kB)\n",
      "Collecting pydeck<1,>=0.8.0b4 (from streamlit)\n",
      "  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)\n",
      "Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\\users\\donyango\\appdata\\local\\programs\\python\\python314\\lib\\site-packages (from streamlit) (6.5.2)\n",
      "Requirement already satisfied: jinja2 in c:\\users\\donyango\\appdata\\local\\programs\\python\\python314\\lib\\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)\n",
      "Requirement already satisfied: jsonschema>=3.0 in c:\\users\\donyango\\appdata\\local\\programs\\python\\python314\\lib\\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.25.1)\n",
      "Requirement already satisfied: narwhals>=1.27.1 in c:\\users\\donyango\\appdata\\local\\programs\\python\\python314\\lib\\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.11.0)\n",
      "Requirement already satisfied: colorama in c:\\users\\donyango\\appdata\\local\\programs\\python\\python314\\lib\\site-packages (from click<9,>=7.0->streamlit) (0.4.6)\n",
      "Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)\n",
      "  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)\n",
      "Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)\n",
      "  Downloading smmap-5.0.2-py3-none-any.whl.metadata (4.3 kB)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\users\\donyango\\appdata\\local\\programs\\python\\python314\\lib\\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\donyango\\appdata\\local\\programs\\python\\python314\\lib\\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\users\\donyango\\appdata\\local\\programs\\python\\python314\\lib\\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in c:\\users\\donyango\\appdata\\local\\programs\\python\\python314\\lib\\site-packages (from requests<3,>=2.27->streamlit) (3.4.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\donyango\\appdata\\local\\programs\\python\\python314\\lib\\site-packages (from requests<3,>=2.27->streamlit) (3.11)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\donyango\\appdata\\local\\programs\\python\\python314\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2.5.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\donyango\\appdata\\local\\programs\\python\\python314\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2025.11.12)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in c:\\users\\donyango\\appdata\\local\\programs\\python\\python314\\lib\\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)\n",
      "Requirement already satisfied: attrs>=22.2.0 in c:\\users\\donyango\\appdata\\local\\programs\\python\\python314\\lib\\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (25.4.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\\users\\donyango\\appdata\\local\\programs\\python\\python314\\lib\\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in c:\\users\\donyango\\appdata\\local\\programs\\python\\python314\\lib\\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in c:\\users\\donyango\\appdata\\local\\programs\\python\\python314\\lib\\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.28.0)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\donyango\\appdata\\local\\programs\\python\\python314\\lib\\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)\n",
      "Downloading streamlit-1.53.0-py3-none-any.whl (9.1 MB)\n",
      "   ---------------------------------------- 0.0/9.1 MB ? eta -:--:--\n",
      "   ---------------------------------------- 0.0/9.1 MB ? eta -:--:--\n",
      "   - -------------------------------------- 0.3/9.1 MB ? eta -:--:--\n",
      "   ---- ----------------------------------- 1.0/9.1 MB 2.6 MB/s eta 0:00:04\n",
      "   ------------ --------------------------- 2.9/9.1 MB 5.0 MB/s eta 0:00:02\n",
      "   -------------- ------------------------- 3.4/9.1 MB 5.6 MB/s eta 0:00:02\n",
      "   ---------------- ----------------------- 3.7/9.1 MB 4.3 MB/s eta 0:00:02\n",
      "   ------------------------- -------------- 5.8/9.1 MB 4.8 MB/s eta 0:00:01\n",
      "   -------------------------- ------------- 6.0/9.1 MB 4.5 MB/s eta 0:00:01\n",
      "   ----------------------------- ---------- 6.8/9.1 MB 4.5 MB/s eta 0:00:01\n",
      "   ---------------------------------- ----- 7.9/9.1 MB 4.3 MB/s eta 0:00:01\n",
      "   ---------------------------------------  8.9/9.1 MB 4.4 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 9.1/9.1 MB 4.3 MB/s  0:00:02\n",
      "Downloading altair-6.0.0-py3-none-any.whl (795 kB)\n",
      "   ---------------------------------------- 0.0/795.4 kB ? eta -:--:--\n",
      "   ---------------------------------------- 795.4/795.4 kB 7.9 MB/s  0:00:00\n",
      "Downloading blinker-1.9.0-py3-none-any.whl (8.5 kB)\n",
      "Downloading cachetools-6.2.4-py3-none-any.whl (11 kB)\n",
      "Downloading click-8.3.1-py3-none-any.whl (108 kB)\n",
      "Downloading gitpython-3.1.46-py3-none-any.whl (208 kB)\n",
      "Downloading gitdb-4.0.12-py3-none-any.whl (62 kB)\n",
      "Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)\n",
      "   ---------------------------------------- 0.0/6.9 MB ? eta -:--:--\n",
      "   ------------- -------------------------- 2.4/6.9 MB 11.8 MB/s eta 0:00:01\n",
      "   ---------------------------- ----------- 5.0/6.9 MB 11.7 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 6.9/6.9 MB 10.7 MB/s  0:00:00\n",
      "Downloading smmap-5.0.2-py3-none-any.whl (24 kB)\n",
      "Downloading tenacity-9.1.2-py3-none-any.whl (28 kB)\n",
      "Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)\n",
      "Downloading watchdog-6.0.0-py3-none-win_amd64.whl (79 kB)\n",
      "Installing collected packages: watchdog, toml, tenacity, smmap, click, cachetools, blinker, pydeck, gitdb, gitpython, altair, streamlit\n",
      "\n",
      "   ----------------------------------------  0/12 [watchdog]\n",
      "   ----------------------------------------  0/12 [watchdog]\n",
      "   --- ------------------------------------  1/12 [toml]\n",
      "   ---------- -----------------------------  3/12 [smmap]\n",
      "   ------------- --------------------------  4/12 [click]\n",
      "   ------------- --------------------------  4/12 [click]\n",
      "   ----------------------- ----------------  7/12 [pydeck]\n",
      "   ----------------------- ----------------  7/12 [pydeck]\n",
      "   ----------------------- ----------------  7/12 [pydeck]\n",
      "   -------------------------- -------------  8/12 [gitdb]\n",
      "   ------------------------------ ---------  9/12 [gitpython]\n",
      "   ------------------------------ ---------  9/12 [gitpython]\n",
      "   ------------------------------ ---------  9/12 [gitpython]\n",
      "   --------------------------------- ------ 10/12 [altair]\n",
      "   --------------------------------- ------ 10/12 [altair]\n",
      "   --------------------------------- ------ 10/12 [altair]\n",
      "   --------------------------------- ------ 10/12 [altair]\n",
      "   ------------------------------------ --- 11/12 [streamlit]\n",
      "   ------------------------------------ --- 11/12 [streamlit]\n",
      "   ------------------------------------ --- 11/12 [streamlit]\n",
      "   ------------------------------------ --- 11/12 [streamlit]\n",
      "   ------------------------------------ --- 11/12 [streamlit]\n",
      "   ------------------------------------ --- 11/12 [streamlit]\n",
      "   ------------------------------------ --- 11/12 [streamlit]\n",
      "   ------------------------------------ --- 11/12 [streamlit]\n",
      "   ------------------------------------ --- 11/12 [streamlit]\n",
      "   ------------------------------------ --- 11/12 [streamlit]\n",
      "   ------------------------------------ --- 11/12 [streamlit]\n",
      "   ------------------------------------ --- 11/12 [streamlit]\n",
      "   ------------------------------------ --- 11/12 [streamlit]\n",
      "   ------------------------------------ --- 11/12 [streamlit]\n",
      "   ------------------------------------ --- 11/12 [streamlit]\n",
      "   ------------------------------------ --- 11/12 [streamlit]\n",
      "   ------------------------------------ --- 11/12 [streamlit]\n",
      "   ------------------------------------ --- 11/12 [streamlit]\n",
      "   ------------------------------------ --- 11/12 [streamlit]\n",
      "   ------------------------------------ --- 11/12 [streamlit]\n",
      "   ------------------------------------ --- 11/12 [streamlit]\n",
      "   ------------------------------------ --- 11/12 [streamlit]\n",
      "   ------------------------------------ --- 11/12 [streamlit]\n",
      "   ---------------------------------------- 12/12 [streamlit]\n",
      "\n",
      "Successfully installed altair-6.0.0 blinker-1.9.0 cachetools-6.2.4 click-8.3.1 gitdb-4.0.12 gitpython-3.1.46 pydeck-0.9.1 smmap-5.0.2 streamlit-1.53.0 tenacity-9.1.2 toml-0.10.2 watchdog-6.0.0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "[notice] A new release of pip is available: 25.2 -> 25.3\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    }
   ],
   "source": [
    "!pip install streamlit "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "43f20c1d-7d9f-4fdc-953a-3896e0506fd9",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-01-18 11:45:47.659 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:47.661 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:48.043 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\donyango\\AppData\\Local\\Programs\\Python\\Python314\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2026-01-18 11:45:48.043 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:48.044 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:48.045 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:48.046 Session state does not function when running a script without `streamlit run`\n",
      "2026-01-18 11:45:48.047 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:48.048 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:48.049 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:48.050 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:48.051 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:48.052 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:48.053 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:48.054 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:48.055 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:48.055 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:48.059 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:48.061 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:48.063 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:48.064 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:48.065 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:48.066 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:48.068 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:48.069 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:48.070 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:48.071 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:48.074 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:48.077 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:48.078 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:48.079 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:45:48.082 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import numpy as np\n",
    "import hashlib\n",
    "import uuid\n",
    "import time\n",
    "\n",
    "st.set_page_config(page_title=\"Aviator Crash Game\", layout=\"centered\")\n",
    "\n",
    "def generate_crash_point():\n",
    "    seed = str(uuid.uuid4())\n",
    "    hash_value = hashlib.sha256(seed.encode()).hexdigest()\n",
    "    number = int(hash_value[:8], 16)\n",
    "    return round(max(1.0, (2**32 / (number + 1))), 2)\n",
    "\n",
    "st.title(\"✈️ Aviator Crash Game\")\n",
    "\n",
    "if \"crash\" not in st.session_state:\n",
    "    st.session_state.crash = generate_crash_point()\n",
    "    st.session_state.multiplier = 1.0\n",
    "    st.session_state.running = False\n",
    "    st.session_state.result = \"\"\n",
    "\n",
    "if st.button(\"START ROUND\"):\n",
    "    st.session_state.crash = generate_crash_point()\n",
    "    st.session_state.multiplier = 1.0\n",
    "    st.session_state.running = True\n",
    "    st.session_state.result = \"\"\n",
    "\n",
    "if st.button(\"CASH OUT\"):\n",
    "    if st.session_state.running:\n",
    "        st.session_state.running = False\n",
    "        st.session_state.result = f\"✅ Cashed out at {st.session_state.multiplier:.2f}x\"\n",
    "\n",
    "placeholder = st.empty()\n",
    "\n",
    "if st.session_state.running:\n",
    "    while st.session_state.multiplier < st.session_state.crash:\n",
    "        st.session_state.multiplier += 0.02\n",
    "        placeholder.metric(\"Multiplier\", f\"{st.session_state.multiplier:.2f}x\")\n",
    "        time.sleep(0.1)\n",
    "\n",
    "    st.session_state.running = False\n",
    "    st.session_state.result = f\"💥 CRASHED at {st.session_state.crash}x\"\n",
    "\n",
    "if st.session_state.result:\n",
    "    st.info(st.session_state.result)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cecd4411-8b09-440f-9f00-236f6268ae98",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
